version: '3'
services:
  spring-contract-stub-runner:
    image: com.github.kbyyd24/ldd-stub-runner:0.0.1
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "9999:9999"
    environment:
      - STUBRUNNER_IDS=com.github.hippoom:ldd-backend-stubs:+:9999
      - STUBRUNNER_REPOSITORY_ROOT=http://localhost:8081/repository/maven-releases/
      - STUBRUNNER_USERNAME=admin
      - STUBRUNNER_PASSWORD=admin123
      - STUBRUNNER_STUBS_MODE=LOCAL

